export const murals = [
  {
    id: 1,
    name: "Dhikr",
    categories: "Mandala with Islamic dua/prayer",
    size: "Diameter 180cm",
    img: "/murals/wall/Dhikr 1.webp",
    hoverImg: "/murals/Dhikr.webp",
  },
  {
    id: 2,
    name: "Bloom",
    categories: "Abstract painting of natural forms",
    size: "L:355cm X H:300cm",
    img: "/murals/wall/Bloom 1.webp",
    hoverImg: "/murals/Bloom.webp",
  },
  {
    id: 3,
    name: "Peony Lines",
    categories: "Line art of a peony flower",
    size: "L:160cm X H:300cm",
    img: "/murals/wall/Peony Lines 1.webp",
    hoverImg: "/murals/Peony Lines.webp",
  },
  {
    id: 4,
    name: "Yin Yang Semi Mandala",
    categories: "Semi mandala with doodled patterns and metallic paints",
    size: "Diameter 160cm",
    img: "/murals/wall/Yin Yang 1.webp",
    hoverImg: "/murals/Yin Yang.webp",
  },
  {
    id: 5,
    name: "Pikachu Switchpanel",
    categories: "Tiny murals painted around switchboard panels",
    size: "L:10cm X H:10cm",
    img: "/murals/wall/Pikachu Switchpanel.webp",
    hoverImg: "/murals/Pikachu Switchpanel.webp",
  },
  {
    id: 6,
    name: "Koala Switchpanel",
    categories: "Tiny murals painted around switchboard panels",
    size: "L:10cm X H:8cm",
    img: "/murals/wall/Koala Switchpanel.webp",
    hoverImg: "/murals/Koala Switchpanel.webp",
  },
];
