export const products = [
  {
    id: 1,
    name: "orange tree",
    img: "/products/Orange Tree-mixed media.webp",
    categories: "Mixed Media",
    dimensions: "Mixed media on canvas, 90cmx60cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Mixed media art with gypsum, exploring patterns in nature. The artwork features an orange tree growing out of a non-flowing water fountain, showing revival or rebirth. The fountain is backed by mosaic-patterned tile ,age.",
    forShow: true,
  },
  {
    id: 2,
    name: "conform 1",
    img: "/products/Conform 1.webp",
    categories: "Mixed Media",
    dimensions:
      "Mixed media on paper, 70cmx50cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Abstract mixed media art with dried roses and metallic gold paint. The artwork symbolizes femininity, power, and conformity in society.",
    forShow: true,
  },
  {
    id: 3,
    name: "conform 2",
    img: "/products/Conform 2.webp",
    categories: "Mixed Media",
    dimensions: "Mixed media on paper, 70cmx50cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Abstract mixed media art with dried roses and metallic gold paint. The artwork symbolizes femininity, power, and conformity in society.",
    forShow: true,
  },
  {
    id: 4,
    name: "cat eyes",
    img: "/products/Cat Eyes.webp",
    categories: "Acrylics",
    dimensions: "Acrylics on canvas, 10cmx10cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Cartoony cat eye painting on tiny easel canvas",
    forShow: true,
  },
  {
    id: 5,
    name: "petunia gold",
    img: "/products/Petunia Gold Leaf.webp",
    thumbnail: "/products/Petunia Gold Leaf thumb.jpg",
    categories: "Mixed Media",
    dimensions: "Mixed media on canvas, Diameter 30cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: false,
    desc: "Bas-relief in gypsum of a peony flower with gold leaf background. Hand modelled with gypsum paste and painted in acrylics.",
    forShow: false,
  },
  {
    id: 6,
    name: "water lilly pond",
    img: "/products/Water lilly Pond.webp",
    thumbnail: "/products/Water lilly Pond thumb.jpg",
    categories: "Acrylics",
    dimensions: "Acrylics on canvas, 40cmx50cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: false,
    desc: "Acrylic painting of water lilies painted with modelling paste in a peacock-blue pond and swirling koi fish. A sense of harmony is found in the contrasting colors of nature.",
    forShow: false,
  },
  {
    id: 7,
    name: "oranges",
    img: "/products/Oranges.webp",
    categories: "Paintings",
    dimensions: "Brush pen on paper, 16cmx23cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Freehand brush pen illustration, with strokes rushed and struck on the paper surface—an experiment of pen strokes and their dramatic effects.",
    forShow: false,
  },
  {
    id: 8,
    name: "kadeer",
    img: "/products/Kadeer-.webp",
    thumbnail: "/products/Kadeer- thumb.jpg",
    categories: "Calligraphy",
    dimensions: "Calligraphy on paper, 21cmx29cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: false,
    desc: "Acrylic calligraphy, 'Wa huwa ala kulli shayin qadeer' (وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ).",
    forShow: false,
  },
  {
    id: 9,
    name: "pet tiger",
    img: "/products/Pet Tiger.webp",
    categories: "Mixed Media",
    dimensions: "Brush pen on paper, 16cmx23cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Freehand brush pen illustration, with strokes rushed and struck on the paper surface—an experiment of pen strokes and their dramatic effects.",
    forShow: false,
  },
  {
    id: 10,
    name: "oriental",
    img: "/products/Oriental.webp",
    thumbnail: "/products/Oriental thumb.jpg",
    categories: "Paintings",
    dimensions: "Acrylics on canvas, 15cmx15cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: false,
    desc: "Arabesque floral motifs.",
    forShow: false,
  },
  {
    id: 11,
    name: "red and fox",
    img: "/products/Red and Fox.webp",
    categories: "Mixed Media",
    dimensions: "Brush pen on paper, 16cmx23cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Freehand brush pen illustration, with strokes rushed and struck on the paper surface—an experiment of pen strokes and their dramatic effects.",
    forShow: false,
  },
  {
    id: 12,
    name: "golden fold",
    img: "/products/Golden Fold.webp",
    thumbnail: "/products/Golden Fold thumb.jpg",
    categories: "Mixed Media",
    dimensions: "Mixed media on canvas, 15cmx15cm",
    ogPrice: 900,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: false,
    desc: "Textured fabric art.",
    forShow: false,
  },
  {
    id: 13,
    name: "be into the wild",
    img: "/products/Be Into the Wild.webp",
    categories: "Illustration",
    dimensions: "Illustration on paper, 40cmx50cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Illustration with  marker pens and brush pens on paper. Inspired  by mountain valleys and wild nature.",
    forShow: true,
  },
  {
    id: 14,
    name: "bismillah",
    img: "/products/Bismillah-.webp",
    thumbnail: "/products/Bismillah- thumb.jpg",
    categories: "Calligraphy",
    dimensions: "Calligraphy on paper, 21cmx29cm",
    ogPrice: 3000,
    offerPrice: 312,
    offer: 50,
    quantity: 1,
    sold: false,
    desc: "Acrylic calligraphy, 'Bismillah al-Rahman al-Rahim' (بِسْمِ ٱللهِ ٱلرَّحْمَٰنِ ٱلرَّحِيْمِ).",
    forShow: false,
  },
  {
    id: 15,
    name: "grow a thought",
    img: "/products/Grow A Thought-painting.webp",
    categories: "Acrylics",
    dimensions: "Acrylics on canvas, 24cmx29cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Painting of a broken statue with plants growing out of it symbolizing regrowth and a metaphor for thoughts that we grow in our mind, which determines the personality of our soul.",
    forShow: false,
  },
  {
    id: 16,
    name: "contrast",
    img: "/products/Contrast.webp",
    thumbnail: "/products/Contrast thumb.jpg",
    categories: "Wooden Panels",
    dimensions: "Linoprint on paper, 15cmx21cm",
    ogPrice: 303,
    offerPrice: 50,
    offer: 50,
    quantity: 1,
    sold: false,
    desc: "Linoprinted art.",
    forShow: false,
  },
  {
    id: 17,
    name: "jameel",
    img: "/products/Jameel1.webp",
    categories: "Calligraphy",
    dimensions: "Calligraphy on canvas, 30cmx15cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Acrylic calligraphy, 'Fa Sabrun Jameel' (فَصَبْرٌ جَمِيلٌ).",
    forShow: false,
  },
  {
    id: 18,
    name: "fathima",
    img: "/products/Fathima.webp",
    categories: "Calligraphy",
    dimensions: "Calligraphy on canvas, 15cmx15cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Acrylic calligraphy, of the name ‘Fathima’.",
    forShow: false,
  },
  {
    id: 19,
    name: "petals of alhamdulillah",
    img: "/products/Alhamdulillah.webp",
    categories: "Calligraphy",
    dimensions: "Calligraphy on canvas, 24cmx29cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Acrylic calligraphy, “Alhamdulillah”(الحمد لله)",
    forShow: true,
  },
  {
    id: 20,
    name: "elements",
    img: "/products/Elements.webp",
    categories: "Calligraphy",
    dimensions: "Linoprint on paper, 30cmx21cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Linoprinted art",
    forShow: true,
  },
  {
    id: 21,
    name: "zone in halos",
    img: "/products/Zone in Halos.webp",
    categories: "Mixed Media",
    dimensions: "Mixed media on paper, 15cmx21cm",
    ogPrice: 30,
    offerPrice: 15,
    offer: 50,
    quantity: 1,
    sold: true,
    desc: "Lady in halos-meditative art illustration",
    forShow: true,
  },
];


export const categories = [
  "All",
  "Calligraphy",
  "Wooden Panels",
  "Digital Art",
  "Paintings",
  "Mixed Media",
];
